#Есть поддержка hex 
messages:
  header: "&6--------| &4&l&a&b&5&8LamaAutoGive &6|--------"
  
  footer: "&6--------| &4&l&a&b&5&8LamaAutoGive &6|--------"
  
  donator-selected: "&4Администратор &6%player% &eвыбрал &6%donator% &eв качестве &4&nсчастливчика &eи ему была награда! /warp case"
commands:

  #Сюда можно вписать команду выдачи доната,кейсов,рублей,рубинов и тд. 
  # %player% это счастливчик который получит ресурсы либо же рубли или же кейсы

  give-donate: "p give %player% 1"
